# Generated by Django 5.0.1 on 2026-02-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JastipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=200)),
                ('toko', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('biaya_jastip', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gambar_url', models.URLField(blank=True)),
                ('status_open', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
