# Generated by Django 5.0.1 on 2026-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jastipitem',
            name='kategori',
            field=models.CharField(choices=[('Sarapan', 'Sarapan'), ('Makan Siang', 'Makan Siang'), ('Makan Malam', 'Makan Malam')], default='Makan Siang', max_length=20),
        ),
    ]
